import dotenv from 'dotenv';

dotenv.config();

const PORT = process.env.PORT || 3000;
const ALLOWED_ORIGINS = process.env.ALLOWED_ORIGINS
  ? process.env.ALLOWED_ORIGINS.split(',')
  : ['http://localhost:3000'];
const JWT_SECRET_KEY = process.env.JWT_SECRET_KEY;
const JWT_REFRESH_KEY = process.env.JWT_REFRESH_KEY;
const NODE_ENV = process.env.NODE_ENV;
const DB_URL = process.env.DB_URL;
const PAYPAL_SANDBOX_CLIENT_ID = process.env.PAYPAL_SANDBOX_CLIENT_ID;
const PAYPAL_LIVE_CLIENT_ID = process.env.PAYPAL_LIVE_CLIENT_ID;
const PAYPAL_SANDBOX_SECRET_KEY = process.env.PAYPAL_SANDBOX_SECRET_KEY;
const PAYPAL_LIVE_SECRET_KEY = process.env.PAYPAL_LIVE_SECRET_KEY;
const PAYPAL_SANDBOX_PARTNER_ID = process.env.PAYPAL_SANDBOX_PARTNER_ID;
const PAYPAL_LIVE_PARTNER_ID = process.env.PAYPAL_LIVE_PARTNER_ID;
const PAYPAL_SANDBOX_PLATFORM_MERCHANT_ID = process.env.PAYPAL_SANDBOX_PLATFORM_MERCHANT_ID;
const PAYPAL_LIVE_PLATFORM_MERCHANT_ID = process.env.PAYPAL_LIVE_PLATFORM_MERCHANT_ID;
const PAYPAL_SANDBOX_BASE_URL = process.env.PAYPAL_SANDBOX_BASE_URL;
const PAYPAL_LIVE_BASE_URL = process.env.PAYPAL_LIVE_BASE_URL;
const BASE_URL = process.env.BASE_URL;
const BREVO_API_KEY = process.env.BREVO_API_KEY;
const GREEN_INVOICE_API_URL = process.env.GREEN_INVOICE_API_URL;
const GREEN_INVOICE_API_KEY = process.env.GREEN_INVOICE_API_KEY;
const GREEN_INVOICE_API_SECRET = process.env.GREEN_INVOICE_API_SECRET;

export { PORT,BASE_URL, ALLOWED_ORIGINS, JWT_SECRET_KEY, JWT_REFRESH_KEY, NODE_ENV, DB_URL,PAYPAL_LIVE_SECRET_KEY,PAYPAL_LIVE_PARTNER_ID,PAYPAL_LIVE_BASE_URL,PAYPAL_LIVE_PLATFORM_MERCHANT_ID, PAYPAL_SANDBOX_CLIENT_ID,PAYPAL_SANDBOX_PLATFORM_MERCHANT_ID,PAYPAL_SANDBOX_PARTNER_ID, PAYPAL_SANDBOX_SECRET_KEY, PAYPAL_SANDBOX_BASE_URL,PAYPAL_LIVE_CLIENT_ID, BREVO_API_KEY,GREEN_INVOICE_API_KEY ,GREEN_INVOICE_API_URL,GREEN_INVOICE_API_SECRET };
