import type { EmailTemplateName } from './types.js';

export const EMAIL_SUBJECTS: Record<EmailTemplateName, string> = {
  WELCOME: 'ברוכים הבאים ל-StudioZ!',
  PASSWORD_RESET: 'איפוס סיסמה',
  EMAIL_VERIFICATION: 'אימות כתובת אימייל',
  ACCOUNT_DEACTIVATION: 'חשבונך בוטל',
  ORDER_CONFIRMATION: 'אישור רכישה',
  PAYOUT_NOTIFICATION: 'אישור תשלום (Payout)',
  REFUND_CONFIRMATION: 'אישור החזר כספי',
  ORDER_CANCELLED: 'ההזמנה בוטלה',
  NEW_BOOKING_VENDOR: 'הזמנה חדשה התקבלה',
  BOOKING_CONFIRMED_CUSTOMER: 'הזמנתך אושרה',
  BOOKING_REMINDER: 'תזכורת להזמנה',
  BOOKING_CANCELLED_CUSTOMER: 'ההזמנה בוטלה',
  BOOKING_CANCELLED_VENDOR: 'הזמנה בוטלה',
  BOOKING_MODIFIED: 'פרטי ההזמנה עודכנו',
  REVIEW_REQUEST: 'איך היה בסטודיו?',
  SUBSCRIPTION_CONFIRMATION: 'המינוי שלך הופעל',
  SUBSCRIPTION_PAYMENT: 'אישור תשלום מינוי',
  SUBSCRIPTION_CANCELLATION: 'המינוי בוטל',
  TRIAL_STARTED: 'תקופת הניסיון שלך התחילה!',
  TRIAL_ENDING: 'תקופת הניסיון שלך עומדת להסתיים',
  TRIAL_CHARGE_FAILED: 'פעולה נדרשת: התשלום נכשל',
  SUBSCRIPTION_PAYMENT_FAILED: 'חיוב מינוי נכשל',
  SUBSCRIPTION_EXPIRING: 'המינוי עומד להסתיים',
  SUBSCRIPTION_UPGRADED: 'המינוי שודרג!',
  SUBSCRIPTION_DOWNGRADED: 'המינוי שונה',
  DOCUMENT_EMAIL: 'מסמך חדש נשלח אליך',
};
